### ISSUE TITLE
Multiple Droplet instances & hooks

### ISSUE THREAD

**Issue by simenheg** [Wildhoney/EmberDroplet#104]
When multiple Droplet component instances exist at the same time, it seems that hooks are triggered for all of them, instead of being triggered in just the component that an event belongs to.

For instance, if there are three Droplet component instances and one of them is used to upload a file, the hooks (`didAdd`, `didUpload`, `didComplete`, and so on) are triggered in all three components.

It would be great if these hooks only triggered in the component they belong to, or at least if there was a way to determine which of the components triggered the events.

**Comment by Truffula** [comment]
In addition, the events are not being unsubscribed, so if a component is removed from the DOM, it still receives the events (which can throw errors).

**Comment by Wildhoney** [comment]
Is there a better way to communicate between Ember components than with events? When I migrated `EmberDroplet` to version 2 of Ember, there wasn't a better way &mdash; but as I don't use Ember day-in-day-out I could have missed something.

**Comment by simenheg** [comment]
@Wildhoney: I think [contextual components](http://emberjs.com/blog/2016/01/15/ember-2-3-released.html#toc_contextual-components) of Ember 2.3 might be worth a look.

Meanwhile I've been using a temporary workaround by [supplying the events with a context](https://github.com/eliksir/EmberDroplet/commit/be04789eb0b6c386c8038d4be6a46f1c878ff8e6).

**Comment by patroqueeet** [comment]
having the same problem. what about a pull request?

**Comment by Wildhoney** [comment]
Pull requests welcome!

**Comment by patroqueeet** [comment]
@simenheg might your approach suitable for a pull request to @Wildhoney ?

**Comment by simenheg** [comment]
@patroqueeet: Maybe.

@Wildhoney: Could you take a look at https://github.com/eliksir/EmberDroplet/commit/be04789eb0b6c386c8038d4be6a46f1c878ff8e6? If it looks like a viable approach to you I can prepare a proper PR.

**Comment by Wildhoney** [comment]
@simenheg it looks good to me 👍 Thanks.

**Comment by Wildhoney** [comment]
Released https://github.com/Wildhoney/EmberDroplet/pull/111 as `v3.1.0`.
