### ISSUE TITLE
how to import in ember cli

### ISSUE THREAD

**Issue by patroqueeet** [Wildhoney/EmberDroplet#110]
I installed it with bower and created a component:

```
import Ember from 'ember';

export default Ember.Component.extend(Droplet, {
    url: location.origin + '/upload'
});
```

I'm now getting the error that Droplet was not imported. I tried `import Droplet from 'ember-droplet/components/' but that failed. how can I fix that?

**Comment by patroqueeet** [comment]
by some reason it started working with the imports you documented. thx anyway

**Comment by dant00ine** [comment]
What was the solution here? Having the same problem. Do we not need an import statement to use the Droplet mixin?

**Comment by patroqueeet** [comment]
I believe restarting my ember watch as well as my grunt processess did the trick as they did not seem to be able to use newly imported imports automatically.

if that does not the trick, here is my grep for the code

templates in django
```
templates/_upload2.html:<script type="text/x-handlebars" data-template-name="components/image-droplet">
templates/_upload2.html:  {{#image-droplet-area}}
templates/_upload2.html:          {{image-droplet-preview image=file}}
templates/_upload2.html:      {{!--- {{image-droplet-input}} ---}}
templates/_upload2.html:  {{/image-droplet-area}}
templates/index.html:  <script src="{{ STATIC_URL }}javascripts/contrib/ember-droplet-mixin.js"></script>
templates/index.html:  <script src="{{ STATIC_URL }}javascripts/contrib/ember-droplet-view.js"></script>
```

js ember code:
```
(.ve)jirsch@codingmachine:/srv/www/vbnet/site$ grep -Ir Droplet ../sitejs/app
../sitejs/app/components/image-droplet.js:export default Ember.Component.extend(Droplet, {
../sitejs/app/components/image-droplet.js:    requestMethod:  Droplet.METHOD.POST,
../sitejs/app/components/image-droplet-preview.js:export default Ember.Component.extend(Droplet.Preview, {
../sitejs/app/components/image-droplet-area.js:export default Ember.Component.extend(Droplet.Area, {
../sitejs/app/components/image-droplet-input.js:export default Ember.Component.extend(Droplet.MultipleInput, {
```

**Comment by dant00ine** [comment]
Super helpful, thank you friend. A little tl;dr for anyone else stuck here -- you don't need import statements in your components; the Droplet mixin is available from the app level.
