### ISSUE TITLE
how to test using selenium

### ISSUE THREAD

**Issue by patroqueeet** [Wildhoney/EmberDroplet#113]
dear, it's slightly offtrack but google/stackoverflow and co did not return anything valuable. does any of you have a hint how to make a test using selenium to ensure my droplet implementation will stay stable?

**Comment by Wildhoney** [comment]
Have you tried to implement Selenium tests for `EmberDroplet`? I haven't so I can't provide any insight into specific hurdles you may encounter.

However if you've tried, then maybe you can list any specific problems you've been having, which I might be able to help you with, as I'm familiar with Selenium.

**Comment by patroqueeet** [comment]
Dear, after even more research found this: looks quite promising. 

http://stackoverflow.com/questions/29381233/how-to-simulate-html5-drag-and-drop-in-selenium-webdriver/29381532#29381532

**Comment by Wildhoney** [comment]
👍
