### ISSUE TITLE
Can we make this an addon?

### ISSUE THREAD

**Issue by rwwagner90** [Wildhoney/EmberDroplet#116]
Just curious why this is not an Ember addon, would be nice to be able to `ember install ember-droplet`

**Comment by Wildhoney** [comment]
I'm not really much of an Ember aficionado any more.

How would I go about registering it as an Ember addon?

**Comment by rwwagner90** [comment]
Hi @Wildhoney, you would have to change the whole structure of things. It would probably be best to start from scratch and use Ember CLI to do `ember addon ember-droplet` which would make a new addon for you. Then you'd need to copy everything over into it.

**Comment by rwwagner90** [comment]
Looking through the code, it feels like it could take quite awhile. Since you don't really do Ember anymore, if you would be interested in transferring ownership to my org, Ship Shape, I could put in the work to get it working as an addon and add you to the org, and we could collaborate on it there. https://github.com/shipshapecode

**Comment by rwwagner90** [comment]
@Wildhoney thoughts?

**Comment by knownasilya** [comment]
Ping

**Comment by leifdejong** [comment]
@Wildhoney whats the word?

**Comment by rwwagner90** [comment]
@Wildhoney you still around?

**Comment by Wildhoney** [comment]
Folks &ndash; if you want to take this forward, please open PRs and I'll happily merge them in. You're all welcome to contribute, and if anybody wants to be added as a contributor, that's cool too 👍

**Comment by rwwagner90** [comment]
@Wildhoney if I'm expected to rewrite the whole thing from scratch, by myself, I'd just start from scratch in my own org. Since you said you don't do Ember anymore, I thought you might be interested in transferring it to my org and collaborating on things there.

**Comment by Wildhoney** [comment]
> I'm not really much of an Ember aficionado any more.

I still *do* Ember.

You're more than happy to fork it to your org and then refactor it. That's open-source. However I'm not **expecting** you to rewrite `EmberDroplet` &ndash; neither unconditionally *or* on the condition that I transfer ownership &ndash; that's just not very open-sourcey.

If however you would *like* to open a PR or become a contributor, then that's cool, too.
