### ISSUE TITLE
Packaging in amd, named-amd, globals etc

### ISSUE THREAD

**Issue by digitalplaywright** [Wildhoney/EmberDroplet#36]
Currently EmberDroplet is only packaged using globals, but amd modules is becoming the prevalent way of packaging components in Ember. Are you interested in changing the packaging to support globals, amd, and named-amd? 

I've followed what @instructure does here as an example on how to achieve the same: 

  - https://github.com/instructure/ic-autocomplete

when packaging my ember-declarative-authorization component:

  - https://github.com/digitalplaywright/ember-declarative-authorization

It was actually not that hard with the added benefit that the code is cleaner.

**Comment by Error404j** [comment]
Its been a few months since you asked, however, for me the correct import was:
```javascript
app.import('bower_components/ember-droplet/dist/ember-droplet.min.js');

**Comment by rupurt** [comment]
It seems like Ember CLI has recently deprecated `Brocfile.js` and you will need to add it to `ember-cli-build.js` e.g.

```javascript
/* global require, module */
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    // Add options here
  });

  // Import ember droplet into global namespace
  app.import('bower_components/ember-droplet/dist/ember-droplet.min.js');

  // more stuff...

  return app.toTree();
};
```
