### ISSUE TITLE
What is expected behavior for file uploads in demo

### ISSUE THREAD

**Issue by sarus** [Wildhoney/EmberDroplet#81]
Very cool looking project!

In the demo you setup if I drag an image onto the target area the file immediately starts to upload and then disappears (the icon disappears) when the upload is complete.  I never need to press the "Upload All" button.  

Is this expected behavior or should files just be queued until the upload button is pressed?

**Comment by Wildhoney** [comment]
Thanks!

It was [caused by this line](https://github.com/Wildhoney/EmberDroplet/blob/master/example/scripts/controller.js#L60) that I added as an example &ndash; but agreed, you should have to click the button to upload in the example! I've commented that line now :+1:

**Comment by sarus** [comment]
Wow that was a fast response haha.  Just downloaded and giving it a whirl.  Thanks for your great contributions to the ember community.

**Comment by Wildhoney** [comment]
Haha :beers: No problem.
