### ISSUE TITLE
Adding options to  JQuery Ajax call

### ISSUE THREAD

**Issue by sarus** [Wildhoney/EmberDroplet#82]
Hello,

I need to add some additional options to the ajax call making the POST.  Specifically I need to add

```
{
     crossDomain: true,
     xhrFields: {
          withCredentials: true
     }
}
```
     
Do you have any suggestions on how to add this in?  I'd like to avoid changing source if possible.  Thanks!

**Comment by sarus** [comment]
Posted to soon.  Found this issue which got me pointed in the right direction #63 

I just added this snippet into the init method of my Controller that implemenets the `DropletController` mixin.

```
init: function(){
        $.ajaxPrefilter(function( options, originalOptions, jqXHR ) {
            // Modify options, control originalOptions, store jqXHR, etc
            options.xhrFields = {
                withCredentials: true
            }
            options.crossDomain = true;
        });
}
```

**Comment by Wildhoney** [comment]
That's cool :+1: Glad you found a way to implement it.
