### ISSUE TITLE
Is there a way to disable the mimetype whitelisting?

### ISSUE THREAD

**Issue by sarus** [Wildhoney/EmberDroplet#83]
Is there a way to disable whitelisting so that any file can be uploaded?

Correct me if I'm wrong but looking at the source it does not look like you can turn off the whitelisting.  

One possibility is to disable the whitelist if `mimeTypes` is undefined or maybe an empty array.  I suppose the empty array would be dangerous as someone might think that means accept no uploads (although that's not very useful haha).

Otherwise it would require another flag that can be.  Something like `disableMimeTypes` or `disableWhiteList`.

**Comment by Wildhoney** [comment]
Agreed! :+1: I think we should do it for when it's `undefined`. Do you see any problems with this? [Do you think](http://en.wikipedia.org/wiki/Principle_of_least_astonishment) that'd be the expected behaviour?

**Comment by sarus** [comment]
It makes sense to me and it shouldn't bite anyone accidentally since you have to explicitly overwrite the existing `mimeTypes`.

**Comment by Wildhoney** [comment]
I've decided to define it as a wildcard (`mimeTypes: ['image/bmp']`), which should be much more self-explanatory than `undefined`. Agreed? :beers:

**Comment by sarus** [comment]
A
