### ISSUE TITLE
win7x64 installation: 'node_modules' is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by scottbeacher** [Wildhoney/EmberDroplet#85]
When I try to install on a windows 7 system I get the following error:

    > ember-droplet@0.9.3 postinstall C:\_Working\node_modules\ember-droplet
    > node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build

    'node_modules' is not recognized as an internal or external command,
    operable program or batch file.
    npm ERR! ember-droplet@0.9.3 postinstall: `node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the ember-droplet@0.9.3 postinstall script.
    npm ERR! This is most likely a problem with the ember-droplet package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls ember-droplet
    npm ERR! There is likely additional logging output above.

    npm ERR! System Windows_NT 6.1.7601
    npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program     Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ember-droplet"
    npm ERR! cwd C:\_Working
    npm ERR! node -v v0.10.29
    npm ERR! npm -v 1.4.14
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     C:\_Working\npm-debug.log
    npm ERR! not ok code 0

Looks like ember-cli had a similar issue that was fixed: 
https://github.com/ember-cli/ember-cli-qunit/issues/2

**Comment by Kuzirashi** [comment]
Same issue here.
~~~~
$ sudo npm install ember-droplet
|
> ember-droplet@0.9.5 postinstall xxx/node_modules/ember-droplet
> node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build

sh: node_modules/bower/bin/bower: Nie ma takiego pliku ani katalogu(no such file or dir)
npm ERR! Linux 3.19.0-12-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "ember-droplet"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ember-droplet@0.9.5 postinstall: `node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the ember-droplet@0.9.5 postinstall script 'node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build'.
npm ERR! This is most likely a problem with the ember-droplet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/bower/bin/bower install && node_modules/grunt-cli/bin/grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-droplet
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    xxx/npm-debug.log
~~~~

**Comment by Wildhoney** [comment]
Sorry folks! I think I've fixed that now with the latest update :+1: Please try again.
