### ISSUE TITLE
Option for case-insensitive extension check?

### ISSUE THREAD

**Issue by AlexMayants** [Wildhoney/EmberDroplet#88]
When we use list of extensions to validate uploaded files, EmberDroplet marks files with valid but upper-case extension as invalid. For example, "1.jpg" passes, but "2.JPG" failes.

There should probably be an option for case-insensitive extension check.

**Comment by Wildhoney** [comment]
I'd argue that the case-insensitivity should be the default behaviour &ndash; please try `v0.10.0` &ndash; I'll add the conditional as part of the refactor when moving to `Ember.Component`.

**Comment by AlexMayants** [comment]
Thank you! It works fine now.
