### ISSUE TITLE
Unclear how to specify options

### ISSUE THREAD

**Issue by simenheg** [Wildhoney/EmberDroplet#91]
It's unclear how options can be specified when instantiating a component that extends `Droplet`. The documentation says:
> Properties that can be defined when instantiating the Ember.Component [...]

This suggests to me that options are set directly as properties on the component, like so:
```
Ember.Component.extend(window.Droplet, { uploadImmediately: true, [...] });
```

Or even:
```
Ember.Component.extend(window.Droplet, { options: { uploadImmediately: true }, [...] });
```

However I was surprised to find that these properties are overridden when the component is instantiated. I think this should be clarified in the documentation, or the behavior changed to keep option properties set on the component.

**Comment by Wildhoney** [comment]
@simenheg Absolutely! Labelled as a bug, as options should be persisted.

**Comment by mattboldt** [comment]
Bumping this, as I am running into the options being overridden too. Is there a version that's Ember 2.0 compatible that doesn't override custom options?

**Comment by Leooo** [comment]
+!

**Comment by Leooo** [comment]
Anyone forked a working version?

**Comment by Wildhoney** [comment]
I've pushed out an emergency release of `v2.0.0` to see if we can get this working. Tests will fail for the time being until we're on the right path. Please give this version a try and let me know if it behaves as expected.

**Comment by Leooo** [comment]
great thanks a lot, will test in the next day or so.

**Comment by Leooo** [comment]
No. trying to understand your use of `````_extends````` now, but this doesn't work on my side.
`````
export default Ember.Component.extend(Droplet,{
  url: "/uploads/upload_resume",
  //...
});
`````

=> $E.url is still the default one

**Comment by Leooo** [comment]
easy short term fix is to set directly the option hash on the extending component, using all the keys of `DEFAULT_OPTIONS`: 
`````
export default Ember.Component.extend(Droplet,{
  options: {
    requestMethod: 'POST',
    maximumSize: Infinity,
    maximumValidFiles: 1,
    uploadImmediately: false,
    includeXFileSize: true,
    useArray: false,
    mimeTypes: ["application/pdf"],
    requestHeaders: {},
    requestPostData: {}
  },
  //..
};
`````

**Comment by rupurt** [comment]
@Leooo I can't seem to get your suggestion to work

**Comment by rupurt** [comment]
I managed to find a solution that works. You can override the initializer and set the options after `Droplet` finishes the initial configuration.

```javascript
export default Ember.Component.extend(Droplet, {
   init: function() {
      this._super.apply(this, arguments);
      this.set("options.uploadImmediately", true);
   }
});
```
