### ISSUE TITLE
Handle multiple backends

### ISSUE THREAD

**Issue by rupurt** [Wildhoney/EmberDroplet#97]
Hi,

We're trying to upgrade from Droplet 0.10.0 to 1.0.1 and are running into major differences. For instance it now assumes that the server response contains a `files` property. We're trying to use it with Wistia and they don't provide this property.

How would you feel about adding an option which passes the response straight through to the `didUpload` hook. e.g.

```javascript
export default Ember.Component.extend(Droplet, {
   options: {
      processResponse: false
   }
});
```

**Comment by Wildhoney** [comment]
I'm actually happy to change the [`response.files`](https://github.com/Wildhoney/EmberDroplet/blob/master/components/Droplet.js#L555) to just `response` by default, as I don't suppose it makes much sense forcing the server to return a specific response.

Do you want to open a PR for this, and I'll push it with the next breaking changes release? As there are a couple of bugs in setting the options that people are encountering.

**Comment by rupurt** [comment]
:+1: I've also got a fix for the option overriding problems that uses `Object.assigns`. I'll submit separate PR's

**Comment by Wildhoney** [comment]
Excellent news! Thanks, @rupurt
