### ISSUE TITLE
Get the DropletModel.file using a $scope.interface.getFiles()

### ISSUE THREAD

**Issue by MaxNatIxiS** [Wildhoney/EmberDroplet#98]
Hey, 
First of all, thanks for this useful angular module !!

I am looking for some help because I have got some troubles using your DropletModel.

1) DropletModel.file is undefined
html :
        <droplet ng-model="interface"></droplet>

Controller : 
        var tmp_listFile = [];
                for(var model in $scope.interface.getFiles()){
                    tmp_listFile.push(model.file);
                    console.log("MODEL FILE",model.file);
                }

         $scope.buildUploadEmail(json,tmp_listFile);

Here, model.file is undefined whereas $scope.interface.getFiles() is not empty :

    $scope.interface.getFiles() : 
           [e.module.directive.controller.r.DropletModel, e.module.directive.controller.r.DropletModel, ...]

2) Can I use my own http post method ?
I already have a http post method which uses a formdata.
Is there any way to use a custom http post method instead of your uploadFiles interface method ?

Thanks

**Comment by rupurt** [comment]
It seems like you may be looking for [`ngDroplet`](https://github.com/Wildhoney/ngDroplet)
